# Generated by Django 3.0.8 on 2021-02-03 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=50)),
                ('card_year', models.IntegerField()),
                ('grading_type', models.CharField(max_length=50)),
                ('graded_score', models.IntegerField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('purchase_fees', models.DecimalField(decimal_places=2, max_digits=7)),
                ('trend', models.CharField(max_length=5)),
                ('card_photo', models.URLField(blank=True, default=None, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
