# Generated by Django 3.1.6 on 2021-02-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210217_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_photo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
