# Generated by Django 3.1.6 on 2021-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_card_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='graded_score',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10')], max_length=3),
        ),
        migrations.AlterField(
            model_name='card',
            name='grading_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
